<style>
  table {
    @apply table-auto;
  }
  th {
    @apply px-4 py-2;
  }
  td {
    @apply border px-4 py-2;
  }
  div {
    @apply rounded-t-lg;
  }
</style>

<p>There aren't going to be any crashes at 2020-5-18</p>
<div>
  <h4>For date 2020-5-19 there are going to be crashes at:</h4>
  <table>
    <thead>
      <tr>
        <th>Hour of the Day</th>
        <th>Number of Crashes</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>0</td>
        <td>32</td>
      </tr>
      <tr>
        <td>1</td>
        <td>25</td>
      </tr>
      <tr>
        <td>2</td>
        <td>1</td>
      </tr>
      <tr>
        <td>7</td>
        <td>2</td>
      </tr>
      <tr>
        <td>9</td>
        <td>1</td>
      </tr>
      <tr>
        <td>10</td>
        <td>7</td>
      </tr>
      <tr>
        <td>11</td>
        <td>13</td>
      </tr>
      <tr>
        <td>12</td>
        <td>7</td>
      </tr>
      <tr>
        <td>13</td>
        <td>33</td>
      </tr>
      <tr>
        <td>14</td>
        <td>79</td>
      </tr>
      <tr>
        <td>15</td>
        <td>5</td>
      </tr>
      <tr>
        <td>16</td>
        <td>6</td>
      </tr>
      <tr>
        <td>17</td>
        <td>1</td>
      </tr>
      <tr>
        <td>18</td>
        <td>3</td>
      </tr>
      <tr>
        <td>19</td>
        <td>1</td>
      </tr>
      <tr>
        <td>20</td>
        <td>8</td>
      </tr>
      <tr>
        <td>21</td>
        <td>39</td>
      </tr>
      <tr>
        <td>22</td>
        <td>10</td>
      </tr>
    </tbody>
  </table>
</div>
<div>
  <h4>For date 2020-5-20 there are going to be crashes at:</h4>
  <table>
    <thead>
      <tr>
        <th>Hour of the Day</th>
        <th>Number of Crashes</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>6</td>
        <td>3</td>
      </tr>
      <tr>
        <td>8</td>
        <td>1</td>
      </tr>
      <tr>
        <td>9</td>
        <td>2</td>
      </tr>
      <tr>
        <td>10</td>
        <td>1</td>
      </tr>
      <tr>
        <td>14</td>
        <td>1</td>
      </tr>
      <tr>
        <td>16</td>
        <td>6</td>
      </tr>
      <tr>
        <td>17</td>
        <td>1</td>
      </tr>
    </tbody>
  </table>
</div>
<div>
  <h4>For date 2020-5-21 there are going to be crashes at:</h4>
  <table>
    <thead>
      <tr>
        <th>Hour of the Day</th>
        <th>Number of Crashes</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>8</td>
        <td>3</td>
      </tr>
      <tr>
        <td>14</td>
        <td>7</td>
      </tr>
      <tr>
        <td>15</td>
        <td>12</td>
      </tr>
      <tr>
        <td>16</td>
        <td>8</td>
      </tr>
      <tr>
        <td>17</td>
        <td>2</td>
      </tr>
      <tr>
        <td>18</td>
        <td>2</td>
      </tr>
    </tbody>
  </table>
</div>
<div>
  <h4>For date 2020-5-16 there are going to be crashes at:</h4>
  <table>
    <thead>
      <tr>
        <th>Hour of the Day</th>
        <th>Number of Crashes</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>11</td>
        <td>20</td>
      </tr>
      <tr>
        <td>12</td>
        <td>1</td>
      </tr>
      <tr>
        <td>13</td>
        <td>11</td>
      </tr>
      <tr>
        <td>15</td>
        <td>12</td>
      </tr>
      <tr>
        <td>18</td>
        <td>29</td>
      </tr>
    </tbody>
  </table>
</div>
<div>
  <h4>For date 2020-5-17 there are going to be crashes at:</h4>
  <table>
    <thead>
      <tr>
        <th>Hour of the Day</th>
        <th>Number of Crashes</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>6</td>
        <td>1</td>
      </tr>
      <tr>
        <td>11</td>
        <td>40</td>
      </tr>
      <tr>
        <td>12</td>
        <td>82</td>
      </tr>
      <tr>
        <td>13</td>
        <td>220</td>
      </tr>
      <tr>
        <td>14</td>
        <td>51</td>
      </tr>
      <tr>
        <td>15</td>
        <td>113</td>
      </tr>
      <tr>
        <td>16</td>
        <td>94</td>
      </tr>
      <tr>
        <td>17</td>
        <td>163</td>
      </tr>
      <tr>
        <td>18</td>
        <td>4</td>
      </tr>
    </tbody>
  </table>
</div>
